# Generated by Django 4.2.1 on 2023-05-20 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_datt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activitie',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('home.base',),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=80, null=True)),
            ],
            bases=('home.base',),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=30)),
                ('short_desc', models.TextField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            bases=('home.base',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('cover_img', models.ImageField(upload_to='teachers/cover-img')),
                ('twitter', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=30)),
                ('google', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('skype', models.CharField(max_length=30)),
                ('internet', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('biography', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='teachers/img')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='home.categorie')),
                ('teacher_activity', models.ManyToManyField(related_name='activity', to='home.activitie')),
            ],
            bases=('home.base',),
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('cover_img', models.ImageField(upload_to='scholarship/cover-img')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship', to='home.categorie')),
            ],
            bases=('home.base',),
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('desc', models.TextField()),
                ('cover_img', models.ImageField(upload_to='research/cover-img')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='home.categorie')),
            ],
            bases=('home.base',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('title', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('cover_img', models.ImageField(upload_to='event/cover-img')),
                ('short_desc', models.TextField()),
                ('desc', models.TextField()),
                ('money', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='event/img')),
                ('slug', models.SlugField(blank=True, max_length=80, null=True)),
                ('teachers', models.ManyToManyField(related_name='event', to='home.teacher')),
            ],
            bases=('home.base',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('title', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='courses')),
                ('short_desc', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('money', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('timeline', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='courses/cover-img')),
                ('desc', models.TextField()),
                ('requirements', models.TextField()),
                ('how_to_apply', models.TextField()),
                ('fee_and_funding_about', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=80, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='home.categorie')),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='home.teacher')),
            ],
            bases=('home.base',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('title', models.CharField(max_length=30)),
                ('short_desc', models.TextField()),
                ('cover_img', models.ImageField(upload_to='blog/cover-img')),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='blog/img')),
                ('slug', models.SlugField(blank=True, max_length=80, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('home.base',),
        ),
    ]
