# Generated by Django 4.2.1 on 2023-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_research_slug_scholarship_slug_alter_blog_cover_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitie',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
