# Generated by Django 4.2.1 on 2023-05-24 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_activitie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
            ],
            bases=('home.base',),
        ),
    ]
